### ISSUE TITLE
After an update configurator does not open

### ISSUE THREAD

**Issue by vickyorlo** [unix-streamdeck/streamdeckui#14]
See below:
```
> streamdeckui
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running, locked to thread]:
main.newEditor({0x0, 0x0, 0x0}, {0x7f7700, 0xc0000c0000})
        streamdeckui/ui.go:39 +0x30d
main.main()
        streamdeckui/main.go:28 +0x195

```

Worked before update/reboot. Daemon seems to start up fine, though the service status does not mention anything about finding a device and my previous config is not loaded onto the device.

**Comment by The-Jonsey** [comment]
hey, sorry it's taken so long, I believe this can sometimes be the result of the connection to the streamdeck not being closed correctly, has it worked since you opened this issue/does it work if you replug the device while the daemon is running

**Comment by vickyorlo** [comment]
This is actually probably a streamdeckd error - restarting streamdeckd, replugging the device, rebooting the computer etc did not help, but something that did actually help was installing the Python based streamdeck-ui (https://timothycrosley.github.io/streamdeck-ui/) and trying to use that. It worked, and when i closed that and opened streamdeckd again, it started working just fine.
